version: "2.1"
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: "^18.17.0"
    steps:
      - cypress/install:
          package-manager: npm
      - cypress/run-tests:
          cypress-command: npx wait-on@latest http://localhost:3001 && npx cypress run
          start-command: npm run build && npm run start
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 18.17.0
